# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy
from scrapy.item import Item, Field


class SpiderCodeItem(scrapy.Item):
    # define the fields for your item here like:
    name = scrapy.Field()


class BeianItem(scrapy.Item):
    """备案信息"""
    企业名称 = scrapy.Field()
    统一社会信用代码 = scrapy.Field()
    企业链接地址 = scrapy.Field()
    企业类型 = scrapy.Field()
    企业营业地址 = scrapy.Field()
    注册地址 = scrapy.Field()
    采集来源省 = scrapy.Field()
    省内或省外 = scrapy.Field()
    登记状态 = scrapy.Field()
    所属地区 = scrapy.Field()
    来源网站 = scrapy.Field()
    网站代码 = scrapy.Field()
    属地类别 = scrapy.Field()

    信息登记编号 = scrapy.Field()
    企业法定代表人 = scrapy.Field()
    进冀负责人 = scrapy.Field()
    驻鄂机构所在地市州 = scrapy.Field()
    备注 = scrapy.Field()
    md5 = scrapy.Field()


class CreditItem(Item):
    企业名称 = scrapy.Field()
    评价机构 = scrapy.Field()
    行业 = scrapy.Field()
    专业 = scrapy.Field()
    信用得分 = scrapy.Field()
    信用等级 = scrapy.Field()
    排名 = scrapy.Field()
    今日得分 = scrapy.Field()
    今日排名 = scrapy.Field()
    六十日得分 = scrapy.Field()
    六十日排名 = scrapy.Field()
    评价年度 = scrapy.Field()
    网站维护代码 = scrapy.Field()
    发布日期 = scrapy.Field()
    有效期 = scrapy.Field()
    省 = scrapy.Field()
    市 = scrapy.Field()
    网站名称 = scrapy.Field()
    年份 = scrapy.Field()
    履约得分 = scrapy.Field()
    投标得分 = scrapy.Field()
    其他扣分 = scrapy.Field()
    综合得分 = scrapy.Field()
    备注 = scrapy.Field()
    统一社会信用代码 = scrapy.Field()
    资质 = scrapy.Field()

    url = scrapy.Field()
    md5 = scrapy.Field()


class AptItem(Item):
    企业名称 = scrapy.Field()
    企业链接地址 = scrapy.Field()
    证书编号 = scrapy.Field()
    资质等级 = scrapy.Field()
    有效期 = scrapy.Field()
    备注 = scrapy.Field()
    网站维护代码 = scrapy.Field()
    网站名称 = scrapy.Field()
    资质类别 = scrapy.Field()
    所属行政区域 = scrapy.Field()
    许可类别及等级 = scrapy.Field()
    许可证号码 = scrapy.Field()
    有效日期 = scrapy.Field()
    联系电话 = scrapy.Field()
    办公地址 = scrapy.Field()
    是否注销 = scrapy.Field()
    许可证编号 = scrapy.Field()
    许可有效期 = scrapy.Field()
    许可机关 = scrapy.Field()
    承装等级 = scrapy.Field()
    承修等级 = scrapy.Field()
    承试等级 = scrapy.Field()
    资质类型 = scrapy.Field()
    所属省市 = scrapy.Field()
    发证日期 = scrapy.Field()
    省市 = scrapy.Field()
    评审类别 = scrapy.Field()
    发证单位 = scrapy.Field()
    有效结束时间 = scrapy.Field()
    核准时间 = scrapy.Field()
    达标等级 = scrapy.Field()
    有效状态 = scrapy.Field()
    公示批次 = scrapy.Field()
    公示时间 = scrapy.Field()
    级别 = scrapy.Field()
    资质编号 = scrapy.Field()
    颁发日期 = scrapy.Field()
    颁发机构 = scrapy.Field()
    证书状态 = scrapy.Field()
    有效期开始 = scrapy.Field()
    有效期终止 = scrapy.Field()
    住所 = scrapy.Field()
    成熟度等级_通用要求 = scrapy.Field()
    会员类型 = scrapy.Field()
    法人代表 = scrapy.Field()
    许可类别和等级 = scrapy.Field()

    url = scrapy.Field()
    md5 = scrapy.Field()


class GuandaoItem(Item):
    企业名称 = scrapy.Field()
    申请内容 = scrapy.Field()
    许可证编号 = scrapy.Field()
    许可机关 = scrapy.Field()
    资质等级 = scrapy.Field()
    资质取得时间 = scrapy.Field()
    资质到期时间 = scrapy.Field()
    网站名称 = scrapy.Field()
    网站代码 = scrapy.Field()
    资质类别 = scrapy.Field()
    同意申请类型 = scrapy.Field()
    所属地址 = scrapy.Field()
    住所 = scrapy.Field()
    营业执照注册号 = scrapy.Field()
    组织机构代码 = scrapy.Field()
    生产地址 = scrapy.Field()
    产品名称 = scrapy.Field()
    备注 = scrapy.Field()
    所在地区 = scrapy.Field()
    设备类别 = scrapy.Field()
    证书注销类型 = scrapy.Field()
    注销日期 = scrapy.Field()
    证书状态 = scrapy.Field()
    有效期至 = scrapy.Field()
    发证日期 = scrapy.Field()
    注销原因 = scrapy.Field()
    级别 = scrapy.Field()
    品种范围 = scrapy.Field()
    审批事项 = scrapy.Field()
    申请类别 = scrapy.Field()
    类别 = scrapy.Field()
    品种 = scrapy.Field()
    参数 = scrapy.Field()
    代表产品 = scrapy.Field()
    施工类型 = scrapy.Field()
    评审机构 = scrapy.Field()
    是否同时换证 = scrapy.Field()
    变更事项 = scrapy.Field()
    变更原因 = scrapy.Field()
    变更前 = scrapy.Field()
    变更后 = scrapy.Field()
    申请人名称 = scrapy.Field()
    Email = scrapy.Field()
    法定代表人 = scrapy.Field()
    联系电话 = scrapy.Field()
    项目 = scrapy.Field()
    统一社会信用代码 = scrapy.Field()
    是否集团公司 = scrapy.Field()
    证书名称 = scrapy.Field()
    发证机关 = scrapy.Field()
    省份 = scrapy.Field()
    产品单元 = scrapy.Field()
    产品品种 = scrapy.Field()
    规格型号 = scrapy.Field()
    产品标准 = scrapy.Field()
    生产线描述 = scrapy.Field()
    注册地址 = scrapy.Field()
    许可类别 = scrapy.Field()
    设备种类 = scrapy.Field()
    许可级别 = scrapy.Field()
    许可类型 = scrapy.Field()
    企业地址 = scrapy.Field()
    联系人 = scrapy.Field()
    批准范围 = scrapy.Field()
    批准项目 = scrapy.Field()
    施工类别 = scrapy.Field()
    子项目 = scrapy.Field()
    项目种类 = scrapy.Field()
    许可有效期 = scrapy.Field()
    单位地址 = scrapy.Field()
    资质名称 = scrapy.Field()
    范围 = scrapy.Field()
    项目种类项目种类 = scrapy.Field()
    申请时间 = scrapy.Field()
    工商登记码 = scrapy.Field()
    法人姓名 = scrapy.Field()
    税务登记号 = scrapy.Field()
    企业链接地址 = scrapy.Field()
    变更日期 = scrapy.Field()
    机构地址 = scrapy.Field()
    制造地址 = scrapy.Field()
    证书类型 = scrapy.Field()
    许可项目 = scrapy.Field()
    有效期 = scrapy.Field()
    设备品种 = scrapy.Field()
    限制条件 = scrapy.Field()
    原设备类别 = scrapy.Field()
    原设备品种 = scrapy.Field()
    原限制条件 = scrapy.Field()
    发证信息 = scrapy.Field()
    建筑类别 = scrapy.Field()
    类型 = scrapy.Field()
    事项编号 = scrapy.Field()
    许可子项目 = scrapy.Field()
    许可参数 = scrapy.Field()
    初取证日期 = scrapy.Field()
    制造_充装_检验地址 = scrapy.Field()
    组织结构代码 = scrapy.Field()
    发证机构 = scrapy.Field()
    单位所在区域 = scrapy.Field()
    参数范围 = scrapy.Field()
    标题 = scrapy.Field()
    发布时间 = scrapy.Field()

    url = scrapy.Field()
    md5 = scrapy.Field()


class AutoItem(scrapy.Item):
    def __setitem__(self, key, value):
        if key not in self.fields:
            self.fields[key] = Field()
        self._values[key] = value
