# -*- coding: utf-8 -*-
import datetime
import re
import time
import scrapy

from spider_code.items import AutoItem


import manager
class Spider(manager.Spider):
    name = 'X--61'
    allowed_domains = ['183.66.171.78:8011']
    start_urls = ['http://183.66.171.78:8011/CX_SGQYMRPM_FJ2.aspx']
    custom_settings = {
        "download_delay":0.5
    }
    post_header = {
        'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
        'Accept-Encoding': 'gzip, deflate',
        'Accept-Language': 'zh-CN,zh;q=0.9',
        'Cache-Control': 'max-age=0',
        'Connection': 'keep-alive',
        # 'Content-Length': '14928',
        'Content-Type': 'application/x-www-form-urlencoded',
        # 'Cookie': 'ASP.NET_SessionId=1eecvi45g3jiwvzclntzeazz',
        'Host': '183.66.171.78:8011',
        'Origin': 'http://183.66.171.78:8011',
        'Referer': 'http://183.66.171.78:8011/CX_SGQYMRPM_FJ2.aspx',
        'Upgrade-Insecure-Requests': '1',
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 '
                      '(KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'}
    post_data = {'GV_SGPM$ctl16$ddlPageGoto': '1',
                 '__EVENTARGUMENT': '',
                 '__EVENTTARGET': 'GV_SGPM$ctl16$ddlPageGoto',
                 '__EVENTVALIDATION': '/wEW/QIC8sWwtQ4Cg/va+AYCyc2k2g0Cyc2k2g0ChKLlrgMC4Iq94gMCxMCT6Q0ChZPZwQwCgNilnQkCy8z5JQK0n9r+AgK7z7OeDQLOldiEDQLB+vLqAQLA+vLqAQLD+vLqAQLC+vLqAQLF+vLqAQLE+vLqAQLH+vLqAQLW+vLqAQLZ+vLqAQLB+rLpAQLB+r7pAQLB+rrpAQLB+obpAQLB+oLpAQLB+o7pAQLB+orpAQLB+pbpAQLB+tLqAQLB+t7qAQLA+rLpAQLA+r7pAQLA+rrpAQLA+obpAQLA+oLpAQLA+o7pAQLA+orpAQLA+pbpAQLA+tLqAQLA+t7qAQLD+rLpAQLD+r7pAQLD+rrpAQLD+obpAQLD+oLpAQLD+o7pAQLD+orpAQLD+pbpAQLD+tLqAQLD+t7qAQLC+rLpAQLC+r7pAQLC+rrpAQLC+obpAQLC+oLpAQLC+o7pAQLC+orpAQLC+pbpAQLC+tLqAQLC+t7qAQLF+rLpAQLF+r7pAQLF+rrpAQLF+obpAQLF+oLpAQLF+o7pAQLF+orpAQLF+pbpAQLF+tLqAQLF+t7qAQLE+rLpAQLE+r7pAQLE+rrpAQLE+obpAQLE+oLpAQLE+o7pAQLE+orpAQLE+pbpAQLE+tLqAQLE+t7qAQLH+rLpAQLH+r7pAQLH+rrpAQLH+obpAQLH+oLpAQLH+o7pAQLH+orpAQLH+pbpAQLH+tLqAQLH+t7qAQLW+rLpAQLW+r7pAQLW+rrpAQLW+obpAQLW+oLpAQLW+o7pAQLW+orpAQLW+pbpAQLW+tLqAQLW+t7qAQLZ+rLpAQLZ+r7pAQLZ+rrpAQLZ+obpAQLZ+oLpAQLZ+o7pAQLZ+orpAQLZ+pbpAQLZ+tLqAQLZ+t7qAQLnu9W+BgKKgvPLCAKRlZHgAgK0/L79BALbxtyLCQL+qfqgAwKFsJi9BQKom4bKDwKf8caUBwKi2OShCQLnu9G+BgKKgv/LCAKRlZ3gAgK0/Lr9BALbxtiLCQL+qcagAwKFsOS9BQKom4LKDwKf8cKUBwKi2OChCQLnu92+BgKKgvvLCAKRlZngAgK0/Ib9BALbxqSKCQL+qcKgAwKFsOC9BQKom47KDwKf8c6UBwKi2OyhCQLnu9m+BgKKgsfLCAKRleXgAgK0/IL9BALbxqCKCQL+qc6gAwKFsOy9BQKom4rKDwKf8cqUBwKi2OihCQLnu6W9BgKKgsPLCAKRleHgAgK0/I79BALbxqyKCQL+qcqgAwKFsOi9BQKom5bKDwKf8daUBwKi2PShCQLnu6G9BgKKgs/LCAKRle3gAgK0/Ir9BALbxqiKCQL+qdagAwKFsPS9BQKom5LKDwKf8dKUBwKi2PChCQLnu629BgKKgsvLCAKRlengAgK0/Jb9BALbxrSKCQL+qdKgAwKFsPC9BQKom57KDwKf8d6UBwKi2PyhCQLnu6m9BgKKgtfLCAKRlfXgAgK0/JL9BALbxrCKCQL+qd6gAwKFsPy9BQKom5rKDwKf8dqUBwKi2PihCQLnu/W+BgKKgpPLCAKRlbHgAgK0/N7+BALbxvyLCQL+qZqgAwKFsLi9BQKom6bKDwKf8eaUBwKi2IShCQLnu/G+BgKKgp/LCAKRlb3gAgK0/Nr+BALbxviLCQL+qeagAwKFsIS9BQKom6LKDwKf8eKUBwKi2IChCQLmu9W+BgKNgvPLCAKQlZHgAgK3/L79BALaxtyLCQLhqfqgAwKEsJi9BQKrm4bKDwKe8caUBwKl2OShCQLmu9G+BgKNgv/LCAKQlZ3gAgK3/Lr9BALaxtiLCQLhqcagAwKEsOS9BQKrm4LKDwKe8cKUBwKl2OChCQLmu92+BgKNgvvLCAKQlZngAgK3/Ib9BALaxqSKCQLhqcKgAwKEsOC9BQKrm47KDwKe8c6UBwKl2OyhCQLmu9m+BgKNgsfLCAKQleXgAgK3/IL9BALaxqCKCQLhqc6gAwKEsOy9BQKrm4rKDwKe8cqUBwKl2OihCQLmu6W9BgKNgsPLCAKQleHgAgK3/I79BALaxqyKCQLhqcqgAwKEsOi9BQKrm5bKDwKe8daUBwKl2PShCQLmu6G9BgKNgs/LCAKQle3gAgK3/Ir9BALaxqiKCQLhqdagAwKEsPS9BQKrm5LKDwKe8dKUBwKl2PChCQLmu629BgKNgsvLCAKQlengAgK3/Jb9BALaxrSKCQLhqdKgAwKEsPC9BQKrm57KDwKe8d6UBwKl2PyhCQLmu6m9BgKNgtfLCAKQlfXgAgK3/JL9BALaxrCKCQLhqd6gAwKEsPy9BQKrm5rKDwKe8dqUBwKl2PihCQLmu/W+BgKNgpPLCAKQlbHgAgK3/N7+BALaxvyLCQLhqZqgAwKEsLi9BQKrm6bKDwKe8eaUBwKl2IShCQLmu/G+BgKNgp/LCAKQlb3gAgK3/Nr+BALaxviLCQLhqeagAwKEsIS9BQKrm6LKDwKe8eKUBwKl2IChCQLpu9W+BgKMgvPLCAKTlZHgAgK2/L79BALdxtyLCQLgqfqgAwKHsJi9BQKqm4bKDwKB8caUBwKk2OShCQLpu9G+BgKMgv/LCAKTlZ3gAgK2/Lr9BALdxtiLCQLgqcagAwKHsOS9BQKqm4LKDwKB8cKUBwKk2OChCQLpu92+BgKMgvvLCAKTlZngAgK2/Ib9BALdxqSKCQLgqcKgAwKHsOC9BQKqm47KDwKB8c6UBwKk2OyhCQLpu9m+BgKMgsfLCAKTleXgAgK2/IL9BALdxqCKCQLgqc6gAwKHsOy9BQKqm4rKDwKB8cqUBwKk2OihCQLpu6W9BgKMgsPLCAKTleHgAgK2/I79BALdxqyKCQLgqcqgAwKHsOi9BQKqm5bKDwKB8daUBwKk2PShCQLpu6G9BgKMgs/LCAKTle3gAgK2/Ir9BALdxqiKCQLgqdagAwKHsPS9BQKqm5LKDwKB8dKUBwKk2PChCQLpu629BgKMgsvLCAKTlengAgK2/Jb9BALdxrSKCQLgqdKgAwKHsPC9BQKqm57KDwKB8d6UBwxJreHfxyyia/mEtdGqLMyPFlRv',
                 '__LASTFOCUS': '',
                 '__VIEWSTATE': '/wEPDwUKLTIwNTk3MTgyNA9kFgICAQ9kFgQCBQ8QZGQWAWZkAgsPPCsADQEADxYEHgtfIURhdGFCb3VuZGceC18hSXRlbUNvdW50Aq0lZBYCZg9kFh4CAQ9kFhRmD2QWAmYPFQEBMWQCAQ8PFgIeBFRleHQFATFkZAICDw8WAh8CBSrph43luoblu7rlt6XnrKzkuInlu7rorr7mnInpmZDotKPku7vlhazlj7hkZAIDDw8WAh8CBQU3OS40MGRkAgQPDxYCHwIFBTE4Ljg2ZGQCBQ8PFgIfAgUFMTcuNzNkZAIGDw8WAh8CBQUxNy42MGRkAgcPZBYCZg8VAQYxMzMuNTlkAggPDxYCHwIFCjIwMTktMTItMjBkZAIJD2QWAmYPFQGJATxhIGhyZWY9ImphdmFzY3JpcHQ6T3BlblNob3coJzYxMDkwRUU4LTMzRTktNEI4RC1BNENBLTg0REJFMTcwMURCNScsJzIwMTkvMTIvMjAgMDoxNzoxMCcpIj48aW1nIGJvcmRlcj0nMCcgc3JjPScvaW1hZ2VzL3Njb3JlLnBuZycgLz48L2E+ZAICD2QWFGYPZBYCZg8VAQEyZAIBDw8WAh8CBQEyZGQCAg8PFgIfAgUk6YeN5bqG5bu65bel5L2P5a6F5bu66K6+5pyJ6ZmQ5YWs5Y+4ZGQCAw8PFgIfAgUFNzcuODBkZAIEDw8WAh8CBQUxOC44MGRkAgUPDxYCHwIFBTE3Ljc0ZGQCBg8PFgIfAgUFMTcuNzBkZAIHD2QWAmYPFQEGMTMyLjA0ZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCc4MTEzRUIxQi1FQTc5LTQ2NDYtQUJFQS02MjA1RUMwNjlGNjEnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCAw9kFhRmD2QWAmYPFQEBM2QCAQ8PFgIfAgUBM2RkAgIPDxYCHwIFJOmHjeW6huW7uuW3pembhuWbouiCoeS7veaciemZkOWFrOWPuGRkAgMPDxYCHwIFBTcxLjM2ZGQCBA8PFgIfAgUFMTguOTFkZAIFDw8WAh8CBQUxNy43MGRkAgYPDxYCHwIFBTE3LjcyZGQCBw9kFgJmDxUBBjEyNS42OWQCCA8PFgIfAgUKMjAxOS0xMi0yMGRkAgkPZBYCZg8VAYkBPGEgaHJlZj0iamF2YXNjcmlwdDpPcGVuU2hvdygnNEEyQzI2OTAtNkU2Qi00NDlDLUExMEMtNDgwNTM2MjA1RDlGJywnMjAxOS8xMi8yMCAwOjE3OjEwJykiPjxpbWcgYm9yZGVyPScwJyBzcmM9Jy9pbWFnZXMvc2NvcmUucG5nJyAvPjwvYT5kAgQPZBYUZg9kFgJmDxUBATRkAgEPDxYCHwIFATRkZAICDw8WAh8CBSbph43luobmlZnogrLlu7rorr4o6ZuG5ZuiKeaciemZkOWFrOWPuGRkAgMPDxYCHwIFBTY0LjYwZGQCBA8PFgIfAgUFMTkuNTNkZAIFDw8WAh8CBQUxNy44NWRkAgYPDxYCHwIFBTE4LjAyZGQCBw9kFgJmDxUBBjEyMC4wMGQCCA8PFgIfAgUKMjAxOS0xMi0yMGRkAgkPZBYCZg8VAYkBPGEgaHJlZj0iamF2YXNjcmlwdDpPcGVuU2hvdygnOENGMzVEMDctMjczQi00MkQ4LUI2Q0ItQjJENTlDOUI5RjhEJywnMjAxOS8xMi8yMCAwOjE3OjEwJykiPjxpbWcgYm9yZGVyPScwJyBzcmM9Jy9pbWFnZXMvc2NvcmUucG5nJyAvPjwvYT5kAgUPZBYUZg9kFgJmDxUBATVkAgEPDxYCHwIFATVkZAICDw8WAh8CBR7kuK3lhrblu7rlt6Xpm4blm6LmnInpmZDlhazlj7hkZAIDDw8WAh8CBQU2NC4zMmRkAgQPDxYCHwIFBTE5LjMwZGQCBQ8PFgIfAgUFMTcuOTBkZAIGDw8WAh8CBQUxNy45MGRkAgcPZBYCZg8VAQYxMTkuNDJkAggPDxYCHwIFCjIwMTktMTItMjBkZAIJD2QWAmYPFQGJATxhIGhyZWY9ImphdmFzY3JpcHQ6T3BlblNob3coJzFGNUU5NTlFLURERDMtNDk1RC05NkNGLTY0NTI3N0Y3MkM3RCcsJzIwMTkvMTIvMjAgMDoxNzoxMCcpIj48aW1nIGJvcmRlcj0nMCcgc3JjPScvaW1hZ2VzL3Njb3JlLnBuZycgLz48L2E+ZAIGD2QWFGYPZBYCZg8VAQE2ZAIBDw8WAh8CBQE2ZGQCAg8PFgIfAgUn5Lit5Zu95bu6562R56ys5LqM5bel56iL5bGA5pyJ6ZmQ5YWs5Y+4ZGQCAw8PFgIfAgUFNjQuNDRkZAIEDw8WAh8CBQUxOC4zN2RkAgUPDxYCHwIFBTE3LjgyZGQCBg8PFgIfAgUFMTcuODRkZAIHD2QWAmYPFQEGMTE4LjQ4ZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCdGQjc3QkU0Ny0wOTBBLTRCNjItQjU1MS02MzYwMzlEM0Q3QTAnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCBw9kFhRmD2QWAmYPFQEBN2QCAQ8PFgIfAgUBN2RkAgIPDxYCHwIFJ+S4reWbveW7uuetkeesrOWFq+W3peeoi+WxgOaciemZkOWFrOWPuGRkAgMPDxYCHwIFBTYyLjgwZGQCBA8PFgIfAgUFMTguMTdkZAIFDw8WAh8CBQUxNy42OGRkAgYPDxYCHwIFBTE3LjgyZGQCBw9kFgJmDxUBBjExNi40N2QCCA8PFgIfAgUKMjAxOS0xMi0yMGRkAgkPZBYCZg8VAYkBPGEgaHJlZj0iamF2YXNjcmlwdDpPcGVuU2hvdygnNzdERDRBMUMtOTA0RC00OTlDLUJEQ0YtMjUyNzM2NTM3MUQyJywnMjAxOS8xMi8yMCAwOjE3OjEwJykiPjxpbWcgYm9yZGVyPScwJyBzcmM9Jy9pbWFnZXMvc2NvcmUucG5nJyAvPjwvYT5kAggPZBYUZg9kFgJmDxUBAThkAgEPDxYCHwIFAThkZAICDw8WAh8CBSTph43luoblu7rlt6XnrKzkuZ3lu7rorr7mnInpmZDlhazlj7hkZAIDDw8WAh8CBQU1OC44OGRkAgQPDxYCHwIFBTE5LjIxZGQCBQ8PFgIfAgUFMTcuNDFkZAIGDw8WAh8CBQUxNy41N2RkAgcPZBYCZg8VAQYxMTMuMDdkAggPDxYCHwIFCjIwMTktMTItMjBkZAIJD2QWAmYPFQGJATxhIGhyZWY9ImphdmFzY3JpcHQ6T3BlblNob3coJ0VCQjIxNjg5LTZBQ0YtNDA0OS1BMzIyLTZBRjgxOTE3MDY5RScsJzIwMTkvMTIvMjAgMDoxNzoxMCcpIj48aW1nIGJvcmRlcj0nMCcgc3JjPScvaW1hZ2VzL3Njb3JlLnBuZycgLz48L2E+ZAIJD2QWFGYPZBYCZg8VAQE5ZAIBDw8WAh8CBQE5ZGQCAg8PFgIfAgUk5Lit5bu65LqU5bGA56ys5LiJ5bu66K6+5pyJ6ZmQ5YWs5Y+4ZGQCAw8PFgIfAgUFNTguNzZkZAIEDw8WAh8CBQUxNi4xNGRkAgUPDxYCHwIFBTE3LjY2ZGQCBg8PFgIfAgUFMTcuMzRkZAIHD2QWAmYPFQEGMTA5LjkwZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCc2OEY1RjM1Qi0zMzc3LTQ0NTYtOUVEOC1CQkM4REU3N0MxOEUnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCCg9kFhRmD2QWAmYPFQECMTBkAgEPDxYCHwIFAjEwZGQCAg8PFgIfAgUe5Lit5bu65LiJ5bGA6ZuG5Zui5pyJ6ZmQ5YWs5Y+4ZGQCAw8PFgIfAgUFNTQuMzBkZAIEDw8WAh8CBQUxOC45MmRkAgUPDxYCHwIFBTE3LjgxZGQCBg8PFgIfAgUFMTcuOThkZAIHD2QWAmYPFQEGMTA5LjAxZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCdCNDE2RTBFOS03NDg2LTQ0RjYtQTQzQS0yRTFDMkZDRDgzRjUnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCCw9kFhRmD2QWAmYPFQECMTFkAgEPDxYCHwIFAjExZGQCAg8PFgIfAgUq6YeN5bqG5bu65bel56ys5YWr5bu66K6+5pyJ6ZmQ6LSj5Lu75YWs5Y+4ZGQCAw8PFgIfAgUFNTIuMjBkZAIEDw8WAh8CBQUxOS40M2RkAgUPDxYCHwIFBTE3Ljc4ZGQCBg8PFgIfAgUFMTcuODNkZAIHD2QWAmYPFQEGMTA3LjI0ZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCc4ODY4RDZBRC05RTBDLTQzMEEtQkM1Ni00MDkxREJBQ0JDMzgnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCDA9kFhRmD2QWAmYPFQECMTJkAgEPDxYCHwIFAjEyZGQCAg8PFgIfAgUq6YeN5bqG5bu65bel56ys5Zub5bu66K6+5pyJ6ZmQ6LSj5Lu75YWs5Y+4ZGQCAw8PFgIfAgUFNTIuMjBkZAIEDw8WAh8CBQUxOC43OWRkAgUPDxYCHwIFBTE3LjU4ZGQCBg8PFgIfAgUFMTcuNjFkZAIHD2QWAmYPFQEGMTA2LjE4ZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCcxMTk4OThDNS1DQjEzLTQ3N0UtOUQ2NC1FOENEQjcxQ0E1NjAnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCDQ9kFhRmD2QWAmYPFQECMTNkAgEPDxYCHwIFAjEzZGQCAg8PFgIfAgUq6YeN5bqG5ouT6L6+5bu66K6+77yI6ZuG5Zui77yJ5pyJ6ZmQ5YWs5Y+4ZGQCAw8PFgIfAgUFNTAuOTRkZAIEDw8WAh8CBQUxOC4zNGRkAgUPDxYCHwIFBTE3LjYzZGQCBg8PFgIfAgUFMTcuMzRkZAIHD2QWAmYPFQEGMTA0LjI0ZAIIDw8WAh8CBQoyMDE5LTEyLTIwZGQCCQ9kFgJmDxUBiQE8YSBocmVmPSJqYXZhc2NyaXB0Ok9wZW5TaG93KCczOUIxODQzOC0wNzNGLTRDNjMtQjNBOC04QzIyNUQ3ODI3NzYnLCcyMDE5LzEyLzIwIDA6MTc6MTAnKSI+PGltZyBib3JkZXI9JzAnIHNyYz0nL2ltYWdlcy9zY29yZS5wbmcnIC8+PC9hPmQCDg8PFgIeB1Zpc2libGVoZGQCDw9kFgJmD2QWEgIBD2QWAmYPFQEENDc4MWQCAw9kFgJmDxUBAjEzZAIFD2QWAmYPFQEBMWQCBw9kFgJmDxUBAzM2OGQCCQ8PZBYCHgZFbmFibGUFBUZhbHNlZAILDw9kFgIfBAUFRmFsc2VkAg0PD2QWAh8EBQRUcnVlZAIPDw9kFgIfBAUEVHJ1ZWQCEQ8QDxYCHwBnZBAV8AIBMQEyATMBNAE1ATYBNwE4ATkCMTACMTECMTICMTMCMTQCMTUCMTYCMTcCMTgCMTkCMjACMjECMjICMjMCMjQCMjUCMjYCMjcCMjgCMjkCMzACMzECMzICMzMCMzQCMzUCMzYCMzcCMzgCMzkCNDACNDECNDICNDMCNDQCNDUCNDYCNDcCNDgCNDkCNTACNTECNTICNTMCNTQCNTUCNTYCNTcCNTgCNTkCNjACNjECNjICNjMCNjQCNjUCNjYCNjcCNjgCNjkCNzACNzECNzICNzMCNzQCNzUCNzYCNzcCNzgCNzkCODACODECODICODMCODQCODUCODYCODcCODgCODkCOTACOTECOTICOTMCOTQCOTUCOTYCOTcCOTgCOTkDMTAwAzEwMQMxMDIDMTAzAzEwNAMxMDUDMTA2AzEwNwMxMDgDMTA5AzExMAMxMTEDMTEyAzExMwMxMTQDMTE1AzExNgMxMTcDMTE4AzExOQMxMjADMTIxAzEyMgMxMjMDMTI0AzEyNQMxMjYDMTI3AzEyOAMxMjkDMTMwAzEzMQMxMzIDMTMzAzEzNAMxMzUDMTM2AzEzNwMxMzgDMTM5AzE0MAMxNDEDMTQyAzE0MwMxNDQDMTQ1AzE0NgMxNDcDMTQ4AzE0OQMxNTADMTUxAzE1MgMxNTMDMTU0AzE1NQMxNTYDMTU3AzE1OAMxNTkDMTYwAzE2MQMxNjIDMTYzAzE2NAMxNjUDMTY2AzE2NwMxNjgDMTY5AzE3MAMxNzEDMTcyAzE3MwMxNzQDMTc1AzE3NgMxNzcDMTc4AzE3OQMxODADMTgxAzE4MgMxODMDMTg0AzE4NQMxODYDMTg3AzE4OAMxODkDMTkwAzE5MQMxOTIDMTkzAzE5NAMxOTUDMTk2AzE5NwMxOTgDMTk5AzIwMAMyMDEDMjAyAzIwMwMyMDQDMjA1AzIwNgMyMDcDMjA4AzIwOQMyMTADMjExAzIxMgMyMTMDMjE0AzIxNQMyMTYDMjE3AzIxOAMyMTkDMjIwAzIyMQMyMjIDMjIzAzIyNAMyMjUDMjI2AzIyNwMyMjgDMjI5AzIzMAMyMzEDMjMyAzIzMwMyMzQDMjM1AzIzNgMyMzcDMjM4AzIzOQMyNDADMjQxAzI0MgMyNDMDMjQ0AzI0NQMyNDYDMjQ3AzI0OAMyNDkDMjUwAzI1MQMyNTIDMjUzAzI1NAMyNTUDMjU2AzI1NwMyNTgDMjU5AzI2MAMyNjEDMjYyAzI2MwMyNjQDMjY1AzI2NgMyNjcDMjY4AzI2OQMyNzADMjcxAzI3MgMyNzMDMjc0AzI3NQMyNzYDMjc3AzI3OAMyNzkDMjgwAzI4MQMyODIDMjgzAzI4NAMyODUDMjg2AzI4NwMyODgDMjg5AzI5MAMyOTEDMjkyAzI5MwMyOTQDMjk1AzI5NgMyOTcDMjk4AzI5OQMzMDADMzAxAzMwMgMzMDMDMzA0AzMwNQMzMDYDMzA3AzMwOAMzMDkDMzEwAzMxMQMzMTIDMzEzAzMxNAMzMTUDMzE2AzMxNwMzMTgDMzE5AzMyMAMzMjEDMzIyAzMyMwMzMjQDMzI1AzMyNgMzMjcDMzI4AzMyOQMzMzADMzMxAzMzMgMzMzMDMzM0AzMzNQMzMzYDMzM3AzMzOAMzMzkDMzQwAzM0MQMzNDIDMzQzAzM0NAMzNDUDMzQ2AzM0NwMzNDgDMzQ5AzM1MAMzNTEDMzUyAzM1MwMzNTQDMzU1AzM1NgMzNTcDMzU4AzM1OQMzNjADMzYxAzM2MgMzNjMDMzY0AzM2NQMzNjYDMzY3AzM2OBXwAgExATIBMwE0ATUBNgE3ATgBOQIxMAIxMQIxMgIxMwIxNAIxNQIxNgIxNwIxOAIxOQIyMAIyMQIyMgIyMwIyNAIyNQIyNgIyNwIyOAIyOQIzMAIzMQIzMgIzMwIzNAIzNQIzNgIzNwIzOAIzOQI0MAI0MQI0MgI0MwI0NAI0NQI0NgI0NwI0OAI0OQI1MAI1MQI1MgI1MwI1NAI1NQI1NgI1NwI1OAI1OQI2MAI2MQI2MgI2MwI2NAI2NQI2NgI2NwI2OAI2OQI3MAI3MQI3MgI3MwI3NAI3NQI3NgI3NwI3OAI3OQI4MAI4MQI4MgI4MwI4NAI4NQI4NgI4NwI4OAI4OQI5MAI5MQI5MgI5MwI5NAI5NQI5NgI5NwI5OAI5OQMxMDADMTAxAzEwMgMxMDMDMTA0AzEwNQMxMDYDMTA3AzEwOAMxMDkDMTEwAzExMQMxMTIDMTEzAzExNAMxMTUDMTE2AzExNwMxMTgDMTE5AzEyMAMxMjEDMTIyAzEyMwMxMjQDMTI1AzEyNgMxMjcDMTI4AzEyOQMxMzADMTMxAzEzMgMxMzMDMTM0AzEzNQMxMzYDMTM3AzEzOAMxMzkDMTQwAzE0MQMxNDIDMTQzAzE0NAMxNDUDMTQ2AzE0NwMxNDgDMTQ5AzE1MAMxNTEDMTUyAzE1MwMxNTQDMTU1AzE1NgMxNTcDMTU4AzE1OQMxNjADMTYxAzE2MgMxNjMDMTY0AzE2NQMxNjYDMTY3AzE2OAMxNjkDMTcwAzE3MQMxNzIDMTczAzE3NAMxNzUDMTc2AzE3NwMxNzgDMTc5AzE4MAMxODEDMTgyAzE4MwMxODQDMTg1AzE4NgMxODcDMTg4AzE4OQMxOTADMTkxAzE5MgMxOTMDMTk0AzE5NQMxOTYDMTk3AzE5OAMxOTkDMjAwAzIwMQMyMDIDMjAzAzIwNAMyMDUDMjA2AzIwNwMyMDgDMjA5AzIxMAMyMTEDMjEyAzIxMwMyMTQDMjE1AzIxNgMyMTcDMjE4AzIxOQMyMjADMjIxAzIyMgMyMjMDMjI0AzIyNQMyMjYDMjI3AzIyOAMyMjkDMjMwAzIzMQMyMzIDMjMzAzIzNAMyMzUDMjM2AzIzNwMyMzgDMjM5AzI0MAMyNDEDMjQyAzI0MwMyNDQDMjQ1AzI0NgMyNDcDMjQ4AzI0OQMyNTADMjUxAzI1MgMyNTMDMjU0AzI1NQMyNTYDMjU3AzI1OAMyNTkDMjYwAzI2MQMyNjIDMjYzAzI2NAMyNjUDMjY2AzI2NwMyNjgDMjY5AzI3MAMyNzEDMjcyAzI3MwMyNzQDMjc1AzI3NgMyNzcDMjc4AzI3OQMyODADMjgxAzI4MgMyODMDMjg0AzI4NQMyODYDMjg3AzI4OAMyODkDMjkwAzI5MQMyOTIDMjkzAzI5NAMyOTUDMjk2AzI5NwMyOTgDMjk5AzMwMAMzMDEDMzAyAzMwMwMzMDQDMzA1AzMwNgMzMDcDMzA4AzMwOQMzMTADMzExAzMxMgMzMTMDMzE0AzMxNQMzMTYDMzE3AzMxOAMzMTkDMzIwAzMyMQMzMjIDMzIzAzMyNAMzMjUDMzI2AzMyNwMzMjgDMzI5AzMzMAMzMzEDMzMyAzMzMwMzMzQDMzM1AzMzNgMzMzcDMzM4AzMzOQMzNDADMzQxAzM0MgMzNDMDMzQ0AzM0NQMzNDYDMzQ3AzM0OAMzNDkDMzUwAzM1MQMzNTIDMzUzAzM1NAMzNTUDMzU2AzM1NwMzNTgDMzU5AzM2MAMzNjEDMzYyAzM2MwMzNjQDMzY1AzM2NgMzNjcDMzY4FCsD8AJnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZxYBZmQYAQUHR1ZfU0dQTQ8UKwAKZGRkZGRkFQEFRkdVSUQUKwANFCsAAQUkQzNFOThCOUYtQTA4Ny00MEYwLUI2RTYtNTU4NkFDOEJDMjM3FCsAAQUkQ0Y4Nzc3ODEtM0JBRi00RjQ4LTg0QkQtMkE5NEQwRDY4RUQ4FCsAAQUkMkUyMjMyMUMtQTdGQi00N0I5LUFFQTgtMjNBNDc3MkM2MTUwFCsAAQUkRjA1MzcxMjUtOTAzRi00RjdCLTk2QkMtRkM3NEE1NjZFMzExFCsAAQUkNDY5MkU0OTctQTM2Ny00MUJDLTk1MzEtRkYyMTE2QzI3MzM0FCsAAQUkMkVBREVFODEtMjM0QS00QTc4LUFFMjItMzUxODYxMzRGQzBBFCsAAQUkOEJGQTk2RjUtOTUzMS00N0NFLTk3NzQtMUZEREYyRjdCODRDFCsAAQUkOTZFNjVBRDctQTY0OS00OEYxLUFGREItMEIxMEZEQzI5MDlCFCsAAQUkRTIwQTVCMDEtQjZGMS00NTUxLTk4NzQtM0MyNTE4MzRGMDAwFCsAAQUkMjY3OUE4NjItRjAxMS00M0ZCLUJDOTYtNkFBRTYzQUYwMUM0FCsAAQUkN0Q4QkJCREQtNjI4RC00ODRBLUI5ODMtMkUxQkFGNDBDNjZGFCsAAQUkMzc1OEM5RDgtMjREMi00NDMyLTg1MjktQUM2RjA5QTVCQjNEFCsAAQUkMTE1MDU3RjgtNERCRi00NUFBLUJDODItMjAzMDE4NkJDNDEyAvACFCsAAQUkQzNFOThCOUYtQTA4Ny00MEYwLUI2RTYtNTU4NkFDOEJDMjM3ZErSPmgxLIk8s30kLBhuXG3zjJQB',
                 '__VIEWSTATEGENERATOR': 'FB897A01',
                 'ddl_qylx': '',
                 'txt_mc': '',
                 'txt_start': ''}
    flag = 1

    def parse(self, response):
        __EVENTVALIDATION = response.xpath('//input[@id="__EVENTVALIDATION"]/@value').extract_first("")
        __VIEWSTATE = response.xpath('//input[@id="__VIEWSTATE"]/@value').extract_first("")
        self.post_data["__EVENTVALIDATION"] = __EVENTVALIDATION
        self.post_data["__VIEWSTATE"] = __VIEWSTATE
        yield scrapy.FormRequest(
            url=response.url,
            headers=self.post_header,
            formdata=self.post_data,
            dont_filter=True,
            callback=self.deal_parse,
        )

    def deal_parse(self, response):
        item = AutoItem()
        trs = response.xpath('//*[@id="GV_SGPM"]/tr[position()>1 and position()<last()]')
        for tr in trs:
            url_conf = tr.xpath('./td[10]/a/@href').extract_first("").strip()
            url_list = re.findall("\('(.*?)'\)", url_conf)[0].split("','")
            fdata = url_list[1].split(" ")[0].replace('/', "-")
            gclx = re.findall("&Gclx=(.*?)&DATE=", response.text)[0]
            now_time = time.strftime("%a %b %d %Y %H:%M:%S", time.localtime())
            url = f"http://183.66.171.78:8011/CX_QYCXDFXX.aspx?QYBM={url_list[0]}&Gclx={gclx}&DATE={fdata}&{now_time} GMT+0800 (中国标准时间)"
            企业名称 = tr.xpath('./td[3]/text()').extract_first("").strip()
            评价机构 = "重庆市建筑企业诚信综合评价"
            行业 = ""
            专业 = ""
            信用得分 = ""
            信用等级 = ""
            排名 = ""
            今日得分 = tr.xpath('./td[8]/text()').extract_first("").strip()
            今日排名 = tr.xpath('./td[2]/text()').extract_first("").strip()
            六十日得分 = ''
            六十日排名 = ''
            评价年度 = ""
            网站维护代码 = "X--61"
            发布日期 =  tr.xpath('./td[9]/text()').extract_first("").strip()
            有效期 = ""
            省 = "四川"
            市 = "重庆"
            网站名称 = "重庆市建筑企业诚信综合评价"
            item['企业名称'] = 企业名称
            item['评价机构'] = 评价机构
            item['行业'] = 行业
            item['专业'] = 专业
            item['信用得分'] = 信用得分
            item['信用等级'] = 信用等级
            item['排名'] = 排名
            item['今日得分'] = 今日得分
            item['今日排名'] = 今日排名
            item['六十日得分'] = 六十日得分
            item['六十日排名'] = 六十日排名
            item['评价年度'] = 评价年度
            item['网站维护代码'] = 网站维护代码
            item['发布日期'] = 发布日期
            item['有效期'] = 有效期
            item['省'] = 省
            item['市'] = 市
            item['网站名称'] = 网站名称
            item['url'] = url
            yield item


        total_pages = int(re.findall("共 (.*?) 页", response.text)[0])
        if self.flag < total_pages:  # 判断是否翻页
            self.flag += 1
            __EVENTVALIDATION = response.xpath('//input[@id="__EVENTVALIDATION"]/@value').extract_first("")
            __VIEWSTATE = response.xpath('//input[@id="__VIEWSTATE"]/@value').extract_first("")
            self.post_data["__EVENTVALIDATION"] = __EVENTVALIDATION
            self.post_data["__VIEWSTATE"] = __VIEWSTATE
            self.post_data["GV_SGPM$ctl16$ddlPageGoto"] = str(self.flag)
            yield scrapy.FormRequest(
                url=response.url,
                headers=self.post_header,
                formdata=self.post_data,
                dont_filter=True,
                callback=self.deal_parse,
            )




if __name__ == '__main__':
    from manager import run
    run(['Credit', 'X--61', 'auto', 1])
